input {
	beats {
		port => 5044
	}  

	tcp {
		port => 50000
	}

	#elastic_agent {
    #	port => 5044
    #	ssl_enabled => true
    #	ssl_certificate_authorities => ["/usr/share/logstash/config/ca.crt"]
    #	ssl_certificate => "/usr/share/logstash/config/elastic.crt"
    #	ssl_key => "/usr/share/logstash/config/elastic.key"
    #	ssl_client_authentication => "optional"
  	#}
}

## Add your filters / logstash plugins configuration here
#filter {
#    if [@metadata][beat] == "apm" {
#        if [processor][event] == "sourcemap" {
#            mutate {
#                add_field => { "[@metadata][index]" => "%{[@metadata][beat]}-%{[@metadata][version]}-%{[processor][event]}" } 
#            }
#        } else {
#            mutate {
#                add_field => { "[@metadata][index]" => "%{[@metadata][beat]}-%{[@metadata][version]}-%{[processor][event]}-%{+yyyy.MM.dd}" } 
#            }
#        }
#    }
#}

output {
	elasticsearch {
		hosts => "http://elasticsearch:9201"
		#hosts => "elasticsearch:9200"
		user => "logstash_internal"
		password => "${LOGSTASH_INTERNAL_PASSWORD}"
		ssl_certificate_authorities => "config/ca.crt"
		data_stream => true
    	ssl_enabled => false
	}
}
